version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-foresight-rcm}"
    image: localstack/localstack-pro:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # External services port range
      - "127.0.0.1:53:53"                # DNS config (optional)
    environment:
      # Activate LocalStack Pro
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:?}

      # Core Configuration
      - DEBUG=${DEBUG:-0}
      - PERSISTENCE=${PERSISTENCE:-1}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR:-local}
      - LOCALSTACK_HOST=${LOCALSTACK_HOST:-localhost.localstack.cloud}

      # Healthcare RCM Specific Services
      - SERVICES=s3,lambda,dynamodb,rds,sns,sqs,apigateway,cloudformation,sts,iam,kms,logs,events,config,securityhub,signer,cloudtrail,batch,elasticache,ssm,secretsmanager,appsync,comprehend,textract,states

      # Security & Compliance Features (Pro)
      - ENFORCE_IAM=1
      - IAM_LOAD_MANAGED_POLICIES=1
      - S3_SKIP_SIGNATURE_VALIDATION=0
      - LAMBDA_CODE_SIGNING_ENABLED=1

      # Healthcare Data Privacy
      - SKIP_SSL_CERT_DOWNLOAD=0
      - SSL_CERT_PATH=/tmp/localstack/server.test.pem

      # Performance Optimization
      - LAMBDA_REMOTE_DOCKER=0
      - LAMBDA_DOCKER_NETWORK=bridge
      - DOCKER_BRIDGE_IP=172.17.0.1

      # Data Persistence for Healthcare Records
      - DATA_DIR=/tmp/localstack/data
      - HOST_TMP_FOLDER=/tmp/localstack

      # Pro Features for Healthcare Compliance
      - DNS_ADDRESS=0.0.0.0
      - DISABLE_CORS_CHECKS=0
      - DISABLE_EVENTS=0

      # CDK Configuration
      - CDK_LAMBDA_TIMEOUT=900
      - LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT=60

    volumes:
      # Persistent data for healthcare records and compliance data
      - "./tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

    networks:
      - localstack-network

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  localstack-network:
    driver: bridge
