projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - lib/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - lib/graphql/types/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: lib/graphql/types/API.ts
        docsFilePath: lib/graphql
        region: us-east-1
        apiId: dpq4kvswpvgyjmvnrygtuzkzjm
        frontend: javascript
        framework: react
        maxDepth: 2
