name: Deploy Infrastructure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  NODE_VERSION: '20'

jobs:
  deploy:
    name: Deploy CDK Infrastructure
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Enable Corepack for Yarn
      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions-CDKDeploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Build infrastructure
        run: |
          cd infra
          yarn build

      - name: Bootstrap CDK (if needed)
        run: |
          cd infra
          yarn cdk bootstrap aws://${{ secrets.AWS_ACCOUNT_ID }}/${{ env.AWS_REGION }}

      - name: Deploy CDK stacks
        run: |
          cd infra
          yarn cdk deploy --all --require-approval never --verbose
        env:
          STAGE_NAME: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

      - name: Output deployment results
        run: |
          echo "Deployment completed successfully!"
          echo "Stage: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}"
