name: Mirror main branch to staging

on:
  push:
    branches: [ main ]

jobs:
  force-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main (with credentials)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Configure git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Force‑push main → staging
        run: git push origin main:staging --force
